version: '3.8'

services:

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: frontend

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - backend
      - frontend