events{}
http {
  server{
	  listen 80;

	  #Backend
          location /api {
                  proxy_pass http://backend:5000;

          }
          location /api/ {
                  proxy_pass http://backend:5000/;

          }

	  #frontEnd
	  location / {
		  root /usr/share/nginx/html;
		  index index.html;
	          
	  }
	  
  }

}

